Word count template in Go
thiagomanel/fpc pull request #26
Opened 2023-07-30 23:58 UTC by diego-aquino

This pull request implements a template in Go of the word count program based on [wc_single_proc.c](https://github.com/thiagomanel/SO/blob/master/process/word_count/wc_single_proc.c). The script [make_dataset.sh](https://github.com/thiagomanel/SO/blob/master/process/word_count/make_dataset) and the file [file2count.data](https://github.com/thiagomanel/SO/blob/master/process/word_count/file2count.data) are also included.

2023-07-31 10:33 UTC, thiagomanel commented on 2023.1/word_count/go/word_count.go
> +func wc(fileContent string) int {
maybe refactor this function to use `SplitAfter`?

2023-07-31 10:34 UTC, thiagomanel requested changes
thanks. I think we can improve a little bit the `wc` function

2023-07-31 18:17 UTC, thiagomanel approved these changes
thanks

2023-07-31 18:18 UTC, thiagomanel commented
> thanks

ignore. A send the message in the wrong PR. Still waiting for the refactored ode :)

2023-07-31 18:43 UTC, diego-aquino commented on 2023.1/word_count/go/word_count.go
> +func wc(fileContent string) int {
Alright, I'll take a look!

2023-07-31 18:44 UTC, diego-aquino commented on 2023.1/word_count/go/word_count.go
> +func wc(fileContent string) int {
@thiagomanel, I've found this native function that splits a string by its whitespaces: https://pkg.go.dev/strings#Fields. What do you think?

2023-07-31 18:53 UTC, diego-aquino commented on 2023.1/word_count/go/word_count.go
> +	// Implement here...
@thiagomanel, to make sure, the main should be empty, right?

2023-07-31 23:55 UTC, thiagomanel commented on 2023.1/word_count/go/word_count.go
> +func wc(fileContent string) int {
it seams a good option. go ahead

2023-07-31 23:57 UTC, thiagomanel commented on 2023.1/word_count/go/word_count.go
> +	// Implement here...
maybe we can code the main function like the old example: it receives a root dir and call wc_dir for each subdirectory.

2023-08-01 01:20 UTC, diego-aquino commented on 2023.1/word_count/go/word_count.go
> +	// Implement here...
Okay, I just added the implementation of `main` based on the example. Could you take a look?

2023-08-01 23:28 UTC, thiagomanel approved these changes
lgtm

2023-08-01 23:28 UTC, merged