Word count template in Java
thiagomanel/fpc pull request #27
Opened 2023-08-06 17:47 UTC by jaugustorufino

Implements a template in Java of the word count program based on [wc_single_proc.c](https://github.com/thiagomanel/SO/blob/master/process/word_count/wc_single_proc.c).

2023-08-06 19:35 UTC, thiagomanel commented on 2023.1/word_count/java/src/main/java/WordCount.java
> +            System.out.println("Usage: java WordCount <root_directory>");
i think we can be more explicit here. what do you think?

```System.err.println("Usage: java WordCount <root_directory>");
 System.exit(1);```

2023-08-06 19:36 UTC, thiagomanel requested changes
thank @jaugustorufino. I've dropped only one small suggestion on arg handling

2023-08-07 22:16 UTC, jaugustorufino commented on 2023.1/word_count/java/src/main/java/WordCount.java
> +            System.out.println("Usage: java WordCount <root_directory>");
Sure, I agree. Thank you for the feedback!

2023-08-07 22:32 UTC, jaugustorufino commented
I just noticed that my IDE is complaining about the missing package declaration in Java Class.
![image](https://github.com/thiagomanel/fpc/assets/70649235/555c95b4-8223-4a67-a2f5-08e268f28a6f)
But when I put this declaration, I've got this executing `gradle runApp`:
```gradle

> Task :runApp FAILED
Error: Could not find or load main class WordCount
Caused by: java.lang.ClassNotFoundException: WordCount

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runApp'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 579ms
2 actionable tasks: 2 executed
```
What do you think? @thiagomanel

2023-08-10 00:26 UTC, thiagomanel approved these changes
lgtm

2023-08-10 00:27 UTC, merged